
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

String key = "app";
String token = "98C9A-E93F3-F3324-9D02E";

Map paramIconesUse;
String paramurltestevelocidade;
String cor;
String corapp2;
String corFonteS;
Colors corFonte;
List preCadastros; 
String paramurlcontratoscm;
String paramurlcontatowhats;
String paramTelefonePrincipal;
String paramsiteprovedor;
String parammsgprecadastro;
double paramlogotipomarginright;
double paramlogotipomarginleft;
String playerId;
String corFundoLogoTipoExibir;
Color corFundoLogoTipo;
String corFundoBackgroundExibir;
Color corFundoBackground;
Color corfontebuttonhome;
Color corfontehome;
String imagemFundoExibir;
String imagemFundo;
String paymentCardcredit;
String paramExibirPreCadastro;
String paramExibirGraficoConsumo;
String paramIconesCustom;
String paramImageLogo;
int paramTemplate;
int imagemFundoExibir2;
String imageFundo2;
List emails;
int fatura;
File logoTipo;
String paramInstagram;
String paramFacebook;
int paramUseTypeOcorrence;
List paramTypeOcorrence;
String cripto;
List telefones = [];
int paramUseindique;
String paramUseindiqueimg;
String paramUseindiqueurl;
Dio dio;
String tempDirPath;